# Токен Telegram-бота
TELEGRAM_TOKEN = "8430063928:AAFidIFAxHZ9zxOpB6I6xHU99-Zt1YZ6zz4"

# Ключ API Itphone
ITPHONE_API_KEY = "ВАШ_API_КЛЮЧ_ITPHONE"

# CryptoBot Token
CRYPTOBOT_TOKEN = "ВАШ_CRYPTOBOT_TOKEN"
